### ISSUE TITLE
芒果TV闪退

### ISSUE THREAD

**Issue by FulLiunian** [wuxianlin/LuckyHooker#5]
01-24 09:18:40.694 I/Xposed  (14473): start Hook MgTV:5602100
01-24 09:18:40.712 I/Xposed  (14473): java.lang.NoSuchMethodError: com.hunantv.player.vod.mvp.VodPlayerView#showJustLookLayout()#exact
01-24 09:18:43.580 E/Xposed  ( 1574): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
01-24 09:18:43.580 E/Xposed  ( 1574): 	at name.caiyao.sporteditor.a.c$6.afterHookedMethod(Unknown Source)
01-24 09:18:43.580 E/Xposed  ( 1574): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
01-24 09:18:43.580 E/Xposed  ( 1574): 	at com.android.server.pm 

.PackageManagerService.queryIntentActivities(<Xposed>)
01-24 09:18:43.580 E/Xposed  ( 1574): 	at com.android.server.pm 

.PackageManagerService.resolveIntent(PackageManagerService.java:4634)
01-24 09:18:43.580 E/Xposed  ( 1574): 	at android.content.pm 

.IPackageManager$Stub.onTransact(IPackageManager.java:628)
01-24 09:18:43.580 E/Xposed  ( 1574): 	at com.android.server.pm 

.PackageManagerService.onTransact(PackageManagerService.java:2938)
01-24 09:18:43.580 E/Xposed  ( 1574): 	at [android.os.Binder.execTransact(Binder.java:453)]
@wuxianlin   芒果TV 版本V5.6.2

优酷6.13.3 中途广告无法过滤

![youku](https://user-images.githubusercontent.com/29416280/35309946-edb84248-00e9-11e8-9e8c-f34432dd9671.jpg)

[xposed_error_20180124_093136.txt](https://github.com/wuxianlin/LuckyHooker/files/1658196/xposed_error_20180124_093136.txt)

xposed 日志文件

芒果TV 复现视频

[芒果TV.zip](https://github.com/wuxianlin/LuckyHooker/files/1658275/TV.zip)

**Comment by FulLiunian** [comment]
![Uploading DB780D8C99A87540678F4EF68E7D8355.jpg…]()
优酷6.13.3 中途广告无法过滤

**Comment by FulLiunian** [comment]
[xposed_error_20180124_093136.txt](https://github.com/wuxianlin/LuckyHooker/files/1658196/xposed_error_20180124_093136.txt)
